In [ ]:
#importing
import numpy as np


In [ ]:

import numpy as np
a=np.ones((8,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:


#random module is sub-package of numpy
A=np.random.rand(1)
print(A)


[0.72911611]


In [ ]:

A=np.random.rand(8,4)   #rand-range is between 0 and 1
print(A)

[[0.47327757 0.19508547 0.97246655 0.22713543]
 [0.04355172 0.99084258 0.60101876 0.58101308]
 [0.20987686 0.54793132 0.00636699 0.17899683]
 [0.5582956  0.34159369 0.75108719 0.74203022]
 [0.26240822 0.45860816 0.65633785 0.98953096]
 [0.12288371 0.31581847 0.97326081 0.07912814]
 [0.07991296 0.95449983 0.84746945 0.16063933]
 [0.14348951 0.85723005 0.46145428 0.28166061]]


In [ ]:

A=np.floor(10*np.random.rand(8,4))   #rand-range is between 0 and 1
print(A)

[[6. 8. 1. 0.]
 [0. 2. 5. 3.]
 [2. 8. 7. 8.]
 [1. 1. 6. 4.]
 [4. 1. 7. 7.]
 [7. 6. 4. 9.]
 [7. 9. 9. 3.]
 [2. 8. 7. 3.]]


In [ ]:

A=np.arange(1,33).reshape(8,4)
print(A)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
#Spliting of an array
print(np.vsplit(A,4))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]]), array([[25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:

print(np.vsplit(A,4))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]]), array([[25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:
print(np.vsplit(A,(3,5)))     #split it after 3rd row and 5th row

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20]]), array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:

print(np.vsplit(A,(3,6)))     #split it after 3rd row and 6th row

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]]), array([[25, 26, 27, 28],
       [29, 30, 31, 32]])]


In [ ]:

A=np.arange(1,33).reshape(4,8)
print(A)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:


print(np.hsplit(A,4))

[array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26]]), array([[ 3,  4],
       [11, 12],
       [19, 20],
       [27, 28]]), array([[ 5,  6],
       [13, 14],
       [21, 22],
       [29, 30]]), array([[ 7,  8],
       [15, 16],
       [23, 24],
       [31, 32]])]


In [ ]:

print(np.hsplit(A,(3,4)))

[array([[ 1,  2,  3],
       [ 9, 10, 11],
       [17, 18, 19],
       [25, 26, 27]]), array([[ 4],
       [12],
       [20],
       [28]]), array([[ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [21, 22, 23, 24],
       [29, 30, 31, 32]])]


In [ ]:

np.pi

3.141592653589793

In [ ]:

A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:

np.rad2deg(A)     #convert radians to degrees

array([ 45.,  60.,  90., 180.])

In [ ]:

A=[45,60,90,180]
np.deg2rad(A)

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:

A=np.sin(1)
print(A)
B=np.cos(1)
print(B)
C=np.tan(1)
print(C)

0.8414709848078965
0.5403023058681398
1.5574077246549023


In [ ]:

st=np.array([23,45,67,89,21,34])

In [ ]:

np.mean(st)

46.5

In [ ]:

np.median(st)

39.5

In [ ]:


np.std(st)

24.452334585202017

In [ ]:

np.var(st)

597.9166666666666

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:

np.linalg.inv(C)    #Sub-package of numpy

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=np.arange(1,25).reshape(6,4)
print(C)
print(np.argmax(C))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
23


In [ ]:
C=np.floor(10*np.random.rand(24).reshape(6,4))
print(C)
print(np.argmax(C))

[[3. 1. 6. 1.]
 [2. 1. 1. 0.]
 [1. 1. 1. 5.]
 [2. 3. 8. 8.]
 [9. 2. 5. 6.]
 [4. 2. 5. 8.]]
16


In [ ]:
C=10*np.random.rand(24).reshape(6,4)
print(C)
print(np.argmax(C))

[[4.59402203 4.97935933 1.84340712 4.09000458]
 [7.59242273 5.64136957 6.62199966 6.08600954]
 [8.36220192 7.24410588 7.4296069  8.48904129]
 [8.23927613 1.6453869  9.38729373 5.90952424]
 [7.3337213  2.64615766 1.95742458 5.95253486]
 [8.10867734 3.09847901 0.38821721 3.21720712]]
14


In [ ]:

print(np.argmax(C,axis=1))  #rows

[1 0 3 2 0 0]


In [ ]:

print(np.argmax(C,axis=0))   #columns

[2 2 3 2]


In [ ]:
print(np.argmin(C))

22


In [ ]:

print(np.argmin(C,axis=0))

[0 3 5 5]


In [ ]:
print(np.argmin(C,axis=1))

[2 1 1 1 2 2]


In [ ]:
#find the indexs where the values are even:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0))

(array([0, 1, 4]),)


In [ ]:

#used only for already sorted list:
a=np.array([6,7,8,9,10])
x=np.searchsorted(a,10)
print(x)

4


In [ ]:
#used only for already unsorted list:
a=np.array([6,2,7,9,8,9,10])
x=np.searchsorted(a,3)       #it is not appilicable for unsorted list
print(x)

2


In [ ]:
#find the indexs which are divisible by 6
a=np.array([24,16,7,17,54,60])
print(np.where(a%6==0))
print(a)

(array([0, 4, 5]),)
[24 16  7 17 54 60]


In [ ]:

#sorting array
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:

arr=np.array([True,False,True])   #FALSE -0 ,TRUE-0
print(np.sort(arr))


[False  True  True]


In [ ]:
#2d sort -sorting happens within row
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))


In [ ]:

#array filter
arr=np.array([40,42,50,44,67,78])
x=[True,False,True,False,True,True]    #filter list
newarr=arr[x]
print(newarr)

[40 50 67 78]


In [ ]:
arr=np.array([40,42,50,44,67,78])  #filter may be list or array
filt=np.where(arr%2==0)
print(filt)

(array([0, 1, 2, 3, 5]),)


In [ ]:
names=np.array(["Sasi","Prasanna","Akhila","Lavanya","Jaya","Dharani"])   #Zip function is used to combine two or more arrays and lists
initals=np.array(["P","N","T","P","T","K"])
for i ,j in zip(initals,names):
  print(i,".",j)

P . Sasi
N . Prasanna
T . Akhila
P . Lavanya
T . Jaya
K . Dharani


In [ ]:
names=np.array(["Sasi","Prasanna","Akhila","Lavanya","Jaya","Dharani"])   #Zip function is used to combine two or more arrays and lists
initals=np.array(["P","N","T","P","T","K"])
rollno=np.array(["5b0","5a6","5c0","5b1","560","5b2"])
for i,j,k in zip(initals,names,rollno):
  print(i,".",j,".",k)


P . Sasi . 5b0
N . Prasanna . 5a6
T . Akhila . 5c0
P . Lavanya . 5b1
T . Jaya . 560
K . Dharani . 5b2


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
a=np.multiply(a1,a2)
print(a)
b=np.divide(a1,a2)
print(b)
c=np.mod(a1,a2)
print(c)
d=np.divmod(a1,a2)
print(d)

[ 200  420  660  920 1200 1500]
[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]
[10 20  8 17  2 10]
(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
a=np.multiply(a1,a2)
print(a)

[ 200  420  660  920 1200 1500]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
b=np.divide(a1,a2)
print(b)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
c=np.mod(a1,a2)
print(c)

[10 20  8 17  2 10]


In [ ]:

a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
d=np.divmod(a1,a2)
print(d)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


In [ ]:

a=1.2
print(np.log(a))   #natural log e

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a))   #log base

0.2630344058337938


In [ ]:

a=1.2
print(np.log10(a))    #log base 10

0.07918124604762482


In [ ]:

a=np.array([1,1.2,3,4])
print(np.log(a))   #natural log e

[0.         0.18232156 1.09861229 1.38629436]


In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log10(a1))    #base 10

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log2(a1))    #base 2

In [ ]:

a2=np.array([5,6,7,10])
x=np.cumprod(a2)
print(x)

[   5   30  210 2100]


In [ ]:
a2=np.array([5,6,7,10])
x=np.cumsum(a2)
print(x)


[ 5 11 18 28]


In [ ]:

a1=np.array([10,15,25,15])    #e2-e1
newarr=np.diff(a2)
print(newarr)


[1 1 3]


In [ ]:

num1=455
num2=665
x=np.lcm(num1,num2)
print(x)

8645


In [ ]:
num1=455
num2=665
x=np.gcd(num1,num2)
print(x)

35


In [ ]:

a=np.array([12,15,60])
gc=np.gcd.reduce(a)    #takes multiple inputs gives single output
print(gc)


3


In [ ]:

a=np.array([12,15,60])
lc=np.lcm.reduce(a)    #takes multiple inputs gives single output
print(lc)

60
